@baseUrl = http://localhost:8091
@baseNetwork = mainnet

###

POST {{baseUrl}}/block HTTP/1.1
Content-Type: application/json

{
  "network_identifier": {
    "blockchain": "MultiversX",
    "network": "{{baseNetwork}}"
  },
  "block_identifier": {
    "index": 10120629
  }
}
