@baseUrl = http://localhost:7091
@baseNetwork = devnet

# The following Construction API example uses the metadata-only approach.
# In this approach, the sender, receiver, amount etc. are provided as "metadata" (instead of as "operations").

###

# The Asserter component requires "operations" to be set, even though below we use the "metadata" to provide all the necessary information.

POST {{baseUrl}}/construction/preprocess HTTP/1.1
Content-Type: application/json

{
    "network_identifier": {
        "blockchain": "Elrond",
        "network": "{{baseNetwork}}"
    },
    "operations": [
        {
            "operation_identifier": {},
            "type": "Transfer"
        }
    ],
    "metadata": {
        "sender": "erd1ldjsdetjvegjdnda0qw2h62kq6rpvrklkc5pw9zxm0nwulfhtyqqtyc4vq",
        "receiver": "erd1testnlersh4z0wsv8kjx39me4rmnvjkwu8dsaea7ukdvvc9z396qykv7z7",
        "amount": "1",
        "currencySymbol": "ROSETTA-057ab4"
    }
}

###

# If gasLimit and gasPrice are not specified, they will receive the default values.

POST {{baseUrl}}/construction/metadata HTTP/1.1
Content-Type: application/json

{
    "network_identifier": {
        "blockchain": "Elrond",
        "network": "{{baseNetwork}}"
    },
    "options": {
        "sender": "erd1ldjsdetjvegjdnda0qw2h62kq6rpvrklkc5pw9zxm0nwulfhtyqqtyc4vq",
        "receiver": "erd1testnlersh4z0wsv8kjx39me4rmnvjkwu8dsaea7ukdvvc9z396qykv7z7",
        "amount": "1",
        "currencySymbol": "ROSETTA-057ab4",
        "gasLimit": 0,
        "gasPrice": 0,
        "data": null
    }
}

###

# The Asserter component requires "operations" to be set, even though below we use the "metadata" to provide all the necessary information.

POST {{baseUrl}}/construction/payloads HTTP/1.1
Content-Type: application/json

{
    "network_identifier": {
        "blockchain": "Elrond",
        "network": "{{baseNetwork}}"
    },
    "operations": [
        {
            "operation_identifier": {},
            "type": "Transfer"
        }
    ],
    "metadata": {
        "amount": "1",
        "chainID": "D",
        "currencySymbol": "ROSETTA-057ab4",
        "data": "RVNEVFRyYW5zZmVyQDUyNGY1MzQ1NTQ1NDQxMmQzMDM1Mzc2MTYyMzRAMDE=",
        "gasLimit": 616000,
        "gasPrice": 1000000000,
        "nonce": 74,
        "receiver": "erd1testnlersh4z0wsv8kjx39me4rmnvjkwu8dsaea7ukdvvc9z396qykv7z7",
        "sender": "erd1ldjsdetjvegjdnda0qw2h62kq6rpvrklkc5pw9zxm0nwulfhtyqqtyc4vq",
        "version": 1
    },
    "suggested_fee": [
        {
            "value": "121000000000000",
            "currency": {
                "symbol": "XeGLD",
                "decimals": 18
            }
        }
    ]
}
